const data = [
  {
    id: 1,
    first_name: 'Twyla',
    last_name: 'Penvarne',
    email: 'tpenvarne0@oakley.com',
    gender: 'Female',
  },
  {
    id: 2,
    first_name: 'Tracey',
    last_name: 'Veare',
    email: 'tveare1@canalblog.com',
    gender: 'Female',
  },
  {
    id: 3,
    first_name: 'Patrizius',
    last_name: 'Crocetti',
    email: 'pcrocetti2@foxnews.com',
    gender: 'Male',
  },
  {
    id: 4,
    first_name: 'Phylys',
    last_name: 'Windrass',
    email: 'pwindrass3@tinyurl.com',
    gender: 'Female',
  },
  {
    id: 5,
    first_name: 'Kent',
    last_name: 'Hammerstone',
    email: 'khammerstone4@bbc.co.uk',
    gender: 'Male',
  },
  {
    id: 6,
    first_name: 'Lazarus',
    last_name: 'Morson',
    email: 'lmorson5@statcounter.com',
    gender: 'Male',
  },
  {
    id: 7,
    first_name: 'Lorianne',
    last_name: 'Murford',
    email: 'lmurford6@zdnet.com',
    gender: 'Female',
  },
  {
    id: 8,
    first_name: 'Clarabelle',
    last_name: 'Gittings',
    email: 'cgittings7@cisco.com',
    gender: 'Female',
  },
  {
    id: 9,
    first_name: 'Emiline',
    last_name: 'Chubb',
    email: 'echubb8@elpais.com',
    gender: 'Female',
  },
  {
    id: 10,
    first_name: 'Lorenza',
    last_name: 'Widdows',
    email: 'lwiddows9@google.fr',
    gender: 'Female',
  },
  {
    id: 11,
    first_name: 'Selma',
    last_name: 'Struan',
    email: 'sstruana@nationalgeographic.com',
    gender: 'Female',
  },
  {
    id: 12,
    first_name: 'Justino',
    last_name: 'Douglas',
    email: 'jdouglasb@blogs.com',
    gender: 'Male',
  },
  {
    id: 13,
    first_name: 'Ephrayim',
    last_name: 'Brealey',
    email: 'ebrealeyc@answers.com',
    gender: 'Male',
  },
  {
    id: 14,
    first_name: 'Harwell',
    last_name: 'Saffer',
    email: 'hsafferd@nasa.gov',
    gender: 'Male',
  },
  {
    id: 15,
    first_name: 'Edin',
    last_name: 'Josowitz',
    email: 'ejosowitze@theatlantic.com',
    gender: 'Female',
  },
  {
    id: 16,
    first_name: 'Brendin',
    last_name: 'Castelluzzi',
    email: 'bcastelluzzif@storify.com',
    gender: 'Male',
  },
  {
    id: 17,
    first_name: 'Ellis',
    last_name: 'Carroll',
    email: 'ecarrollg@shutterfly.com',
    gender: 'Male',
  },
  {
    id: 18,
    first_name: 'Yetta',
    last_name: 'Reolfi',
    email: 'yreolfih@geocities.com',
    gender: 'Female',
  },
  {
    id: 19,
    first_name: 'Mannie',
    last_name: 'Dobrowlski',
    email: 'mdobrowlskii@nhs.uk',
    gender: 'Male',
  },
  {
    id: 20,
    first_name: 'Kenneth',
    last_name: 'McKintosh',
    email: 'kmckintoshj@cisco.com',
    gender: 'Male',
  },
];
export default data;
